### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-vim#69]
> Subtask of arcticicestudio/nord#55

Adapt to the MIT license migration of the main [Nord][nord] project. Detailed information can be found in the main task ticket.

### Tasks

* [x] Update all license SVG badges
* [x] Update the `LICENSE.md` content
* [x] Update- and simplify all source code comment header

[nord]: https://github.com/arcticicestudio/nord
